import type { Metadata } from "next";
import { LegalShell } from "../legal-shell";

export const metadata: Metadata = {
  title: "Privacy Notice — Washd",
  description: "How Washd collects, uses, shares and protects personal data.",
  alternates: { canonical: "/privacy", languages: { "en-MY": "/privacy", "ms-MY": "/privacy/bm", "zh-CN": "/privacy/zh", "ko-KR": "/privacy/ko" } },
};

export default function PrivacyPage() {
  return (
    <LegalShell policyPath="/privacy" eyebrow="Your data" title="Privacy Notice" intro="This notice explains how Washd collects, uses, discloses, stores and protects personal data when you visit our website, create an account, make a payment or use our laundry service.">
      <section><h2>1. Who is responsible for your data?</h2><p>Washd is the data controller for the personal data described in this notice. You can contact us at <a href="mailto:washdmy@gmail.com">washdmy@gmail.com</a>, call or WhatsApp <a href="https://wa.me/60176494749">017-649 4749</a>, or write to us through the enquiry form on this website.</p></section>
      <section><h2>2. Personal data we collect</h2><p>Depending on how you interact with Washd, we may collect:</p><ul><li>your name, email address, telephone number, residence, unit and collection-point information;</li><li>account identifiers, login and security information;</li><li>membership, add-on, billing status and Stripe transaction references—we do not store your full card number;</li><li>bag identifiers, garment or item counts, collection details, service history, photographs used for service verification and care requests;</li><li>enquiry messages, support conversations and preferences; and</li><li>technical and security information such as browser, device, IP address, timestamps and authentication activity.</li></ul></section>
      <section><h2>3. Where the data comes from</h2><p>We receive data directly from you when you register, subscribe, submit a form or contact us; from our team when we collect and process your laundry; automatically when you use our website or account; and from payment and technology providers when they confirm a transaction, login or system event.</p></section>
      <section><h2>4. Why we process it</h2><p>We process personal data to:</p><ul><li>create and secure your account;</li><li>provide collections, garment care, tracking, returns and customer support;</li><li>process subscriptions, add-ons, payments, cancellations and refunds;</li><li>send service, security and account communications;</li><li>respond to enquiries and prepare custom plans;</li><li>prevent fraud, investigate incidents and protect customers, staff and the service; and</li><li>maintain records and comply with legal, accounting, tax and regulatory obligations.</li></ul><p>Where marketing consent is required, we will ask before sending promotional messages. You may opt out at any time.</p></section>
      <section><h2>5. Is providing the data required?</h2><p>Fields identified as required are necessary to create your account, provide the requested service or respond to an enquiry. If you do not provide them, we may be unable to complete that request. Optional information helps us tailor collections or support and may be left blank.</p></section>
      <section><h2>6. Who we disclose it to</h2><p>We disclose only the data reasonably needed to service providers and authorised people supporting Washd, including Supabase for accounts and operational data, Stripe for payment processing, Google Firebase for website hosting, communication providers, building or collection-point personnel where necessary to complete a collection, professional advisers and public authorities where disclosure is required or permitted by law. We do not sell personal data.</p></section>
      <section><h2>7. International processing</h2><p>Some technology providers may process or store data outside Malaysia. We make such transfers only where permitted by applicable Malaysian data-protection law and take reasonable steps to use reputable providers, contractual protection and safeguards appropriate to the data and transfer.</p></section>
      <section><h2>8. Security and retention</h2><p>We use access controls, encrypted connections, restricted administrator permissions and service-provider security measures. No system can be guaranteed completely secure. We retain data only for as long as needed for the purposes above, to resolve disputes and to meet applicable legal, accounting and tax requirements. Electronic trade transaction records are retained for at least three years where required by law. Data is then deleted or anonymised where reasonably practicable.</p></section>
      <section><h2>9. Your choices and rights</h2><p>Subject to applicable law, you may ask whether we hold your data, request access or correction, withdraw consent, object to direct marketing, ask us to restrict or stop certain processing, or request data portability where that right applies. Email <a href="mailto:washdmy@gmail.com?subject=Personal%20data%20request">washdmy@gmail.com</a> with “Personal data request” in the subject. We may need to verify your identity before acting.</p></section>
      <section><h2>10. Cookies and account storage</h2><p>The website uses storage necessary to keep members securely signed in and operate account features. We will ask for consent before introducing non-essential advertising or analytics cookies where consent is required.</p></section>
      <section><h2>11. Changes and complaints</h2><p>We may update this notice when our service or legal obligations change and will post the updated date here. Please contact us first if you have a concern so we can investigate. You may also contact Malaysia’s Personal Data Protection Department.</p></section>
    </LegalShell>
  );
}
