"use client";

import Link from "next/link";
import { useSiteContent } from "./use-site-content";
import { siteUrl } from "@/lib/site-url";

const planDescriptionsMs: Record<string, string> = {
  starter: "Satu beg 5 kg untuk dibasuh, dikeringkan dan dilipat sekali seminggu.",
  active: "Satu beg 5 kg untuk dibasuh, dikeringkan dan dilipat dua kali seminggu.",
  professional: "Satu beg 7 kg dan empat helai kemeja bergosok sekali seminggu.",
  executive: "Satu beg 7 kg dan tujuh helai kemeja bergosok sekali seminggu.",
};

const addonNamesMs: Record<string, string> = {
  "extra-shirts": "4 helai kemeja bergosok tambahan",
  "extra-bag": "Satu beg 5 kg tambahan",
  "fragrance-free": "Penjagaan tanpa pewangi",
  "priority-return": "Pemulangan keutamaan 24 jam",
};

export function ServiceInformationContent({ locale }: { locale: "en" | "ms" }) {
  const { content, plans, addons } = useSiteContent();
  const ms = locale === "ms";
  const serviceArea = ms && content.contact.serviceArea === "Selected residential buildings in Kuala Lumpur"
    ? "Bangunan kediaman terpilih di Kuala Lumpur"
    : content.contact.serviceArea;

  return <>
    <section><h2>{ms ? "1. Pembekal dan laman web" : "1. Supplier and website"}</h2><div><p>{ms ? <>Perkhidmatan ini ditawarkan oleh {content.contact.legalName || "Washd"} melalui <a href={siteUrl}>{siteUrl}</a>. Alamat e-mel ialah <a href={`mailto:${content.contact.email}`}>{content.contact.email}</a> dan nombor telefon/WhatsApp ialah <a href={`https://wa.me/${content.contact.whatsappNumber}`}>{content.contact.phoneDisplay}</a>.</> : <>This service is offered by {content.contact.legalName || "Washd"} through <a href={siteUrl}>{siteUrl}</a>. The email address is <a href={`mailto:${content.contact.email}`}>{content.contact.email}</a> and the telephone/WhatsApp number is <a href={`https://wa.me/${content.contact.whatsappNumber}`}>{content.contact.phoneDisplay}</a>.</>}</p>{content.contact.registeredAddress && <p>{ms ? "Alamat tempat perdagangan: " : "Place of business: "}{content.contact.registeredAddress}</p>}<p>{ms ? "Kawasan perkhidmatan semasa: " : "Current service area: "}{serviceArea}.</p></div></section>
    <section><h2>{ms ? "2. Ciri utama dan harga penuh" : "2. Main features and full prices"}</h2><div><p>{ms ? "Pelan keahlian semasa ialah:" : "The current membership plans are:"}</p><ul>{plans.map((plan) => <li key={plan.id}><strong>{plan.name} - RM {plan.price_rm} {ms ? "sebulan" : "per month"}:</strong> {ms ? planDescriptionsMs[plan.id] || plan.description : plan.description}.</li>)}</ul><p>{ms ? "Tambahan bulanan pilihan:" : "Optional monthly add-ons:"}</p><ul>{addons.map((addon) => <li key={addon.id}><strong>{ms ? addonNamesMs[addon.id] || addon.name : addon.name} - RM {addon.price_rm} {ms ? "sebulan" : "per month"}.</strong></li>)}</ul><p>{ms ? "Harga yang ditunjukkan termasuk pengumpulan dan pemulangan di tempat pengumpulan bangunan yang disahkan. Jumlah penuh bagi pelan dan tambahan terpilih, termasuk apa-apa cukai atau caj lain yang terpakai, dipaparkan sebelum bayaran disahkan. Tiada caj tambahan akan dikenakan tanpa persetujuan anda." : "Displayed prices include collection and return at the confirmed building collection point. The complete total for the selected plan and add-ons, including any applicable tax or other charge, is displayed before payment is confirmed. No additional charge will be imposed without your agreement."}</p></div></section>
    <section><h2>{ms ? "3. Kaedah dan masa bayaran" : "3. Payment method and timing"}</h2><div><p>{ms ? "Bayaran dibuat dalam Ringgit Malaysia melalui halaman pembayaran Stripe yang selamat menggunakan kad atau kaedah bayaran lain yang dipaparkan oleh Stripe. Jumlah pelan dan tambahan berulang secara bulanan sehingga dibatalkan. Washd tidak menyimpan nombor penuh kad." : "Payment is made in Malaysian Ringgit through secure Stripe-hosted checkout using a card or another payment method displayed by Stripe. The plan and selected add-ons recur monthly until cancelled. Washd does not store the complete card number."}</p></div></section>
    <section><h2>{ms ? "4. Pembekalan perkhidmatan" : "4. Supply of the service"}</h2><div><p>{ms ? "Beg dihantar sebelum 9:30 pagi pada hari laluan bangunan yang disahkan dan biasanya tersedia untuk diambil pada 5:30 petang dua hari kemudian: Isnin ke Rabu atau Rabu ke Jumaat. Jadual khusus bangunan anda akan disahkan sebelum perkhidmatan bermula. Kelewatan material akan dimaklumkan." : "Bags are dropped by 9:30am on the confirmed building route day and are normally ready at 5:30pm two days later: Monday to Wednesday or Wednesday to Friday. Your building-specific schedule is confirmed before service starts. Material delays will be communicated."}</p></div></section>
    <section><h2>{ms ? "5. Terma, pembatalan dan pembetulan" : "5. Terms, cancellation and corrections"}</h2><div><p>{ms ? <>Baca <Link href="/terms/bm">Terma Perkhidmatan</Link> sebelum membuat bayaran. Anda boleh mengubah pelan dan tambahan atau kembali dari Stripe sebelum mengesahkan bayaran. Selepas pesanan dibuat, hubungi Washd dengan segera untuk membetulkan kesilapan. Pembatalan memerlukan sekurang-kurangnya dua minggu notis sebelum tempoh perkhidmatan seterusnya.</> : <>Read the <Link href="/terms">Service Terms</Link> before payment. You can change the plan and add-ons or return from Stripe before confirming payment. After an order is made, contact Washd promptly to correct an error. Cancellation requires at least two weeks’ notice before the next service period.</>}</p></div></section>
    <section><h2>{ms ? "6. Pengakuterimaan dan rekod" : "6. Acknowledgement and records"}</h2><div><p>{ms ? "Bayaran yang berjaya diakui pada skrin, dalam akaun Washd dan melalui rekod/resit Stripe. Washd menyimpan rekod transaksi perdagangan elektronik sekurang-kurangnya tiga tahun apabila dikehendaki undang-undang." : "A successful payment is acknowledged on screen, in the Washd account and through the Stripe transaction/receipt record. Washd retains electronic trade transaction records for at least three years where required by law."}</p></div></section>
    <section><h2>{ms ? "7. Aduan dan remedi" : "7. Complaints and remedies"}</h2><div><p>{ms ? <>Aduan atau permintaan pembetulan boleh dihantar melalui <a href={`mailto:${content.contact.email}`}>{content.contact.email}</a> atau WhatsApp <a href={`https://wa.me/${content.contact.whatsappNumber}`}>{content.contact.phoneDisplay}</a>. Jika perkhidmatan tidak munasabah sesuai atau tidak seperti yang ditawarkan, Washd akan menyiasat dan memberikan remedi yang adil mengikut keadaan dan undang-undang yang terpakai. Lihat juga <Link href="/care-guarantee/bm">Jaminan Penjagaan Washd</Link>.</> : <>Send a complaint or correction request to <a href={`mailto:${content.contact.email}`}>{content.contact.email}</a> or WhatsApp <a href={`https://wa.me/${content.contact.whatsappNumber}`}>{content.contact.phoneDisplay}</a>. If a service is not reasonably fit or is not supplied as offered, Washd will investigate and provide a fair remedy according to the circumstances and applicable law. See the <Link href="/care-guarantee">Washd Care Guarantee</Link>.</>}</p></div></section>
    <section><h2>{ms ? "8. Penjagaan dan keselamatan" : "8. Care and safety"}</h2><div><p>{ms ? "Washd mematuhi label penjagaan dan amalan penjagaan pakaian profesional yang munasabah. Barang berbahaya, tercemar, menyalahi undang-undang atau tidak sesuai tidak boleh dimasukkan. Jika agensi berwibawa menetapkan standard keselamatan atau kesihatan yang terpakai kepada perkhidmatan, Washd akan mematuhinya." : "Washd follows care labels and reasonable professional garment-care practices. Hazardous, contaminated, illegal or unsuitable items must not be included. Where a competent authority specifies a safety or health standard applicable to the service, Washd will follow it."}</p></div></section>
  </>;
}
