import type { Metadata } from "next";
import Link from "next/link";
import { LegalShell } from "../../legal-shell";

export const metadata: Metadata = { title: "Terma Perkhidmatan — Washd", description: "Terma keahlian dobi, pengumpulan, bayaran dan pembatalan Washd.", alternates: { canonical: "/terms/bm", languages: { "en-MY": "/terms", "ms-MY": "/terms/bm", "zh-CN": "/terms/zh", "ko-KR": "/terms/ko" } } };

export default function TermsBmPage() {
  return <LegalShell policyPath="/terms" locale="ms" eyebrow="Jelas dari awal" title="Terma Perkhidmatan" intro="Terma ini terpakai apabila anda membuka akaun Washd, membeli keahlian atau tambahan, atau menyerahkan barangan kepada kami untuk pengumpulan dan penjagaan.">
    <section><h2>1. Perkhidmatan</h2><p>Washd menyediakan perkhidmatan pengumpulan dan pemulangan dobi berulang di bangunan kediaman terpilih di Kuala Lumpur. Ketersediaan bergantung pada laluan aktif, tempat pengumpulan dan kapasiti perkhidmatan. Butiran pelan sebelum bayaran menyatakan saiz beg, kekerapan, bilangan pakaian bergosok, tambahan, harga dan jadual pengumpulan semasa.</p></section>
    <section><h2>2. Akaun dan kelayakan</h2><p>Anda mesti memberikan maklumat perhubungan, kediaman dan pengumpulan yang tepat serta menjaga keselamatan log masuk. Akaun adalah peribadi kepada ahli dan tidak boleh dikongsi. Anda mestilah berumur sekurang-kurangnya 18 tahun atau mempunyai kebenaran ibu bapa atau penjaga sah untuk melanggan.</p></section>
    <section><h2>3. Keahlian, harga dan bayaran</h2><p>Harga dipaparkan dalam Ringgit Malaysia sebelum pembayaran. Keahlian diperbaharui setiap bulan sehingga dibatalkan. Stripe memproses bayaran menggunakan kaedah yang anda berikan. Dengan mengesahkan pembayaran, anda membenarkan caj berulang bagi harga pelan dan tambahan berulang terpilih. Apa-apa cukai atau caj tambahan yang tidak dapat dielakkan akan dipaparkan sebelum bayaran jika berkenaan.</p><p>Jika bayaran gagal, kami boleh mencuba semula, meminta anda mengemas kini kaedah bayaran, menjeda pengumpulan atau menamatkan keahlian. Pembayaran yang berjaya disahkan pada skrin dan dalam akaun Washd.</p></section>
    <section><h2>4. Pembatalan dan bayaran balik</h2><p>Anda boleh meminta pembatalan melalui portal pengebilan atau dengan menghubungi Washd. Berikan sekurang-kurangnya dua minggu notis sebelum tempoh perkhidmatan seterusnya. Pembatalan biasanya berkuat kuasa pada akhir tempoh pengebilan yang telah dibayar; permintaan lewat mungkin berkuat kuasa bagi tempoh berikutnya.</p><p>Caj keahlian biasanya tidak dikembalikan selepas tempoh perkhidmatan bermula atau pengumpulan yang termasuk telah digunakan. Kami akan membetulkan caj pendua atau tidak tepat dan mempertimbangkan bayaran balik jika Washd tidak dapat menyediakan perkhidmatan yang dibeli. Tiada apa-apa dalam terma ini mengehadkan hak atau remedi yang tidak boleh dikecualikan di bawah undang-undang pengguna Malaysia.</p></section>
    <section><h2>5. Pengumpulan dan pemulangan</h2><p>Letakkan beg Washd yang bernombor dan tertutup di tempat pengumpulan yang disahkan sebelum masa ditetapkan. Beg lewat mungkin dipindahkan ke pengumpulan seterusnya. Beg yang dihantar sebelum 9:30 pagi pada laluan Isnin biasanya tersedia pada 5:30 petang Rabu; penghantaran Rabu biasanya tersedia pada 5:30 petang Jumaat. Masa ini ialah anggaran dan boleh berubah kerana akses bangunan, keperluan penjagaan pakaian, isu peralatan, cuaca atau kejadian di luar kawalan munasabah. Kelewatan material akan dimaklumkan melalui butiran akaun anda.</p><p>Anda bertanggungjawab mengambil barangan yang dipulangkan dengan segera dan memastikan maklumat akses serta pengumpulan adalah terkini.</p></section>
    <section><h2>6. Barangan dan tanggungjawab pelanggan</h2><p>Periksa semua poket dan keluarkan wang tunai, barang kemas, dokumen, elektronik, benda tajam dan barangan berharga. Maklumkan barang halus, kesan kotoran, kebimbangan warna luntur atau penjagaan khas sebelum pengumpulan. Jangan serahkan barangan tercemar, berbahaya, menyalahi undang-undang atau diserang perosak. Washd boleh menolak barangan yang tidak selamat atau tidak sesuai.</p><p>Kami mengikuti label penjagaan dan pertimbangan profesional yang munasabah. Sesetengah kotoran, haus, pemindahan warna, pengecutan atau kelemahan sedia ada tidak dapat diperbetulkan dengan selamat. Lihat <Link href="/care-guarantee/bm">Jaminan Penjagaan Washd</Link> bagi cara laporan dan siasatan.</p></section>
    <section><h2>7. Komunikasi</h2><p>Kami boleh menghubungi anda melalui e-mel, telefon atau WhatsApp berkenaan pengumpulan, penjejakan, bayaran, keselamatan dan sokongan. Mesej perkhidmatan ialah sebahagian daripada operasi keahlian. Mesej promosi akan menyediakan cara untuk menarik diri apabila dikehendaki.</p></section>
    <section><h2>8. Perubahan pelan atau perkhidmatan</h2><p>Kami boleh mengemas kini laluan, masa pengumpulan, ciri perkhidmatan atau harga masa hadapan. Notis awal yang munasabah akan diberikan bagi perubahan material yang menjejaskan keahlian berbayar sedia ada. Perubahan tidak mengubah bayaran yang telah diselesaikan tanpa persetujuan anda kecuali jika dikehendaki undang-undang.</p></section>
    <section><h2>9. Tanggungjawab dan kejadian di luar kawalan</h2><p>Washd bertanggungjawab menyediakan perkhidmatan dengan penjagaan dan kemahiran yang munasabah. Kami tidak bertanggungjawab atas kelewatan atau kegagalan akibat kejadian di luar kawalan munasabah, atau kerugian akibat arahan tidak tepat, sifat barangan yang tidak dimaklumkan, barang berharga dalam poket atau pelanggaran terma ini. Tiada apa-apa di sini mengecualikan liabiliti yang tidak boleh dikecualikan di sisi undang-undang.</p></section>
    <section><h2>10. Hubungan dan undang-undang</h2><p>Soalan, permintaan pembatalan dan aduan boleh dihantar kepada <a href="mailto:washdmy@gmail.com">washdmy@gmail.com</a> atau WhatsApp <a href="https://wa.me/60176494749">017-649 4749</a>. Terma ini ditadbir oleh undang-undang Malaysia. Kami akan cuba menyelesaikan aduan secara langsung dan adil terlebih dahulu.</p></section>
  </LegalShell>;
}
