import type { Metadata } from "next";
import { LegalShell } from "../legal-shell";

export const metadata: Metadata = { title: "Service Terms — Washd", description: "Terms for Washd laundry memberships, collections, payments and cancellations.", alternates: { canonical: "/terms", languages: { "en-MY": "/terms", "ms-MY": "/terms/bm", "zh-CN": "/terms/zh", "ko-KR": "/terms/ko" } } };

export default function TermsPage() {
  return (
    <LegalShell policyPath="/terms" eyebrow="Clear from the start" title="Service Terms" intro="These terms apply when you create a Washd account, purchase a membership or add-on, or give items to us for collection and care.">
      <section><h2>1. The service</h2><p>Washd provides recurring laundry collection and return services at selected residential buildings in Kuala Lumpur. Availability depends on an active route, collection point and service capacity. The plan detail shown before payment states the included bag size, frequency, pressed pieces, add-ons, price and current collection rhythm.</p></section>
      <section><h2>2. Accounts and eligibility</h2><p>You must provide accurate contact, residence and collection information and keep your login secure. An account is personal to the member and should not be shared. You must be at least 18 years old or have permission from a parent or legal guardian to subscribe.</p></section>
      <section><h2>3. Memberships, prices and payment</h2><p>Prices are displayed in Malaysian Ringgit before checkout. A membership renews monthly until cancelled. Stripe processes payment using the method you provide. By confirming checkout, you authorise the recurring plan price and selected recurring add-ons. Any taxes or unavoidable additional charges will be shown before payment where applicable.</p><p>If payment fails, we may retry payment, ask you to update the payment method, pause collections or end the membership. A successful checkout is confirmed on screen and in your Washd account.</p></section>
      <section><h2>4. Cancellation and refunds</h2><p>You may request cancellation through the billing portal or by contacting Washd. Please give at least two weeks’ notice before the next service period. Cancellation normally takes effect at the end of the paid billing period; a late request may take effect for the following period.</p><p>Membership charges are normally non-refundable once the service period has begun or included collections have been used. We will correct duplicate or incorrect charges and consider refunds where Washd cannot provide the purchased service. Nothing in these terms limits rights or remedies that cannot lawfully be excluded under Malaysian consumer law.</p></section>
      <section><h2>5. Collections and returns</h2><p>Place your sealed, numbered Washd bag at the confirmed collection point by the stated time. Late bags may move to the next available collection. A bag dropped by 9:30am on a confirmed Monday route is normally ready at 5:30pm Wednesday; a Wednesday drop is normally ready at 5:30pm Friday. Returns are estimates and can change because of building access, garment-care requirements, equipment issues, weather or events outside reasonable control. We will communicate material delays using the contact details on your account.</p><p>You are responsible for collecting returned items promptly and for keeping access and collection information current.</p></section>
      <section><h2>6. Items and customer responsibilities</h2><p>Check all pockets and remove cash, jewellery, documents, electronics, sharp objects and valuables. Tell us about delicate items, stains, colour-fastness concerns or special care before collection. Do not submit contaminated, hazardous, illegal or pest-infested items. Washd may refuse an unsafe or unsuitable item.</p><p>We follow available care labels and reasonable professional judgement. Some stains, wear, dye transfer, shrinkage or pre-existing weakness cannot be safely corrected. See the <a href="/care-guarantee">Washd Care Guarantee</a> for reporting and investigation details.</p></section>
      <section><h2>7. Communications</h2><p>We may contact you by email, telephone or WhatsApp about collections, tracking, payments, security and support. Service messages are part of operating the membership. Promotional messages will include a way to opt out where required.</p></section>
      <section><h2>8. Changes to plans or service</h2><p>We may update routes, collection times, service features or future prices. We will give reasonable advance notice of a material change affecting an existing paid membership. Changes do not alter a completed payment without your agreement except where required by law.</p></section>
      <section><h2>9. Responsibility and events beyond control</h2><p>Washd is responsible for providing the service with reasonable care and skill. We are not responsible for delay or failure caused by events outside reasonable control, or for loss caused by inaccurate instructions, undeclared item characteristics, valuables left in pockets or breach of these terms. Nothing here excludes liability that cannot lawfully be excluded.</p></section>
      <section><h2>10. Contact and governing law</h2><p>Questions, cancellation requests and complaints can be sent to <a href="mailto:washdmy@gmail.com">washdmy@gmail.com</a> or WhatsApp <a href="https://wa.me/60176494749">017-649 4749</a>. These terms are governed by the laws of Malaysia. We will first try to resolve any complaint directly and fairly.</p></section>
    </LegalShell>
  );
}
