import type { Metadata } from "next";
import { LegalShell } from "../../legal-shell";

export const metadata: Metadata = {
  title: "Notis Privasi — Washd",
  description: "Cara Washd mengumpul, menggunakan, berkongsi dan melindungi data peribadi.",
  alternates: { canonical: "/privacy/bm", languages: { "en-MY": "/privacy", "ms-MY": "/privacy/bm", "zh-CN": "/privacy/zh", "ko-KR": "/privacy/ko" } },
};

export default function PrivacyBmPage() {
  return (
    <LegalShell policyPath="/privacy" locale="ms" eyebrow="Data anda" title="Notis Privasi" intro="Notis ini menerangkan cara Washd mengumpul, menggunakan, menzahirkan, menyimpan dan melindungi data peribadi apabila anda melawat laman web, membuka akaun, membuat bayaran atau menggunakan perkhidmatan dobi kami.">
      <section><h2>1. Siapa yang bertanggungjawab terhadap data anda?</h2><p>Washd ialah pengawal data bagi data peribadi yang diterangkan dalam notis ini. Hubungi kami melalui <a href="mailto:washdmy@gmail.com">washdmy@gmail.com</a>, telefon atau WhatsApp <a href="https://wa.me/60176494749">017-649 4749</a>, atau borang pertanyaan di laman web ini.</p></section>
      <section><h2>2. Data peribadi yang kami kumpulkan</h2><p>Bergantung pada cara anda berinteraksi dengan Washd, kami mungkin mengumpulkan:</p><ul><li>nama, alamat e-mel, nombor telefon, kediaman, unit dan maklumat tempat pengumpulan;</li><li>pengenal akaun serta maklumat log masuk dan keselamatan;</li><li>keahlian, tambahan, status pengebilan dan rujukan transaksi Stripe—kami tidak menyimpan nombor penuh kad anda;</li><li>pengenal beg, kiraan pakaian atau item, butiran pengumpulan, sejarah perkhidmatan, gambar pengesahan perkhidmatan dan permintaan penjagaan;</li><li>mesej pertanyaan, perbualan sokongan dan keutamaan; dan</li><li>maklumat teknikal dan keselamatan seperti pelayar, peranti, alamat IP, cap masa dan aktiviti pengesahan.</li></ul></section>
      <section><h2>3. Sumber data</h2><p>Kami menerima data secara terus daripada anda semasa pendaftaran, langganan, penghantaran borang atau apabila anda menghubungi kami; daripada pasukan kami semasa pengumpulan dan pemprosesan dobi; secara automatik apabila anda menggunakan laman web atau akaun; dan daripada penyedia bayaran serta teknologi apabila mereka mengesahkan transaksi, log masuk atau peristiwa sistem.</p></section>
      <section><h2>4. Tujuan pemprosesan</h2><p>Kami memproses data peribadi untuk:</p><ul><li>mewujudkan dan melindungi akaun anda;</li><li>menyediakan pengumpulan, penjagaan pakaian, penjejakan, pemulangan dan khidmat pelanggan;</li><li>memproses langganan, tambahan, bayaran, pembatalan dan bayaran balik;</li><li>menghantar komunikasi perkhidmatan, keselamatan dan akaun;</li><li>menjawab pertanyaan serta menyediakan pelan tersuai;</li><li>mencegah penipuan, menyiasat insiden dan melindungi pelanggan, kakitangan serta perkhidmatan; dan</li><li>menyimpan rekod dan memenuhi kewajipan undang-undang, perakaunan, cukai serta kawal selia.</li></ul><p>Jika persetujuan pemasaran diperlukan, kami akan memintanya sebelum menghantar mesej promosi. Anda boleh menarik diri pada bila-bila masa.</p></section>
      <section><h2>5. Adakah data wajib diberikan?</h2><p>Ruangan yang ditandakan wajib diperlukan untuk membuka akaun, menyediakan perkhidmatan yang diminta atau menjawab pertanyaan. Tanpanya, kami mungkin tidak dapat memenuhi permintaan tersebut. Maklumat pilihan boleh dibiarkan kosong.</p></section>
      <section><h2>6. Pihak yang menerima data</h2><p>Kami hanya menzahirkan data yang munasabah diperlukan kepada penyedia perkhidmatan dan individu yang diberi kuasa, termasuk Supabase bagi akaun dan data operasi, Stripe bagi pemprosesan bayaran, Google Firebase bagi pengehosan laman web, penyedia komunikasi, kakitangan bangunan atau tempat pengumpulan apabila perlu, penasihat profesional dan pihak berkuasa apabila dibenarkan atau dikehendaki undang-undang. Kami tidak menjual data peribadi.</p></section>
      <section><h2>7. Pemprosesan antarabangsa</h2><p>Sesetengah penyedia teknologi mungkin memproses atau menyimpan data di luar Malaysia. Pemindahan tersebut hanya dibuat apabila dibenarkan oleh undang-undang perlindungan data Malaysia yang terpakai, dan kami mengambil langkah munasabah untuk menggunakan penyedia bereputasi, perlindungan kontrak serta langkah yang sesuai dengan data dan pemindahan.</p></section>
      <section><h2>8. Keselamatan dan penyimpanan</h2><p>Kami menggunakan kawalan akses, sambungan terenkripsi, kebenaran pentadbir terhad dan langkah keselamatan penyedia perkhidmatan. Tiada sistem yang boleh dijamin selamat sepenuhnya. Data disimpan hanya selama diperlukan bagi tujuan di atas, penyelesaian pertikaian dan keperluan undang-undang, perakaunan serta cukai. Rekod transaksi perdagangan elektronik disimpan sekurang-kurangnya tiga tahun apabila dikehendaki undang-undang. Selepas tempoh berkenaan, data dipadam atau dinyahkenal pasti apabila munasabah.</p></section>
      <section><h2>9. Pilihan dan hak anda</h2><p>Tertakluk pada undang-undang, anda boleh bertanya sama ada kami memegang data anda, meminta akses atau pembetulan, menarik balik persetujuan, membantah pemasaran langsung, meminta pemprosesan tertentu dihadkan atau dihentikan, atau meminta kemudahalihan data jika hak itu terpakai. E-mel <a href="mailto:washdmy@gmail.com?subject=Permintaan%20data%20peribadi">washdmy@gmail.com</a> dengan tajuk “Permintaan data peribadi”. Kami mungkin perlu mengesahkan identiti anda.</p></section>
      <section><h2>10. Kuki dan storan akaun</h2><p>Laman web menggunakan storan yang diperlukan untuk memastikan ahli kekal log masuk dengan selamat dan untuk menjalankan ciri akaun. Kami akan meminta persetujuan sebelum memperkenalkan kuki pengiklanan atau analitik yang tidak penting apabila persetujuan diperlukan.</p></section>
      <section><h2>11. Perubahan dan aduan</h2><p>Kami mungkin mengemas kini notis ini apabila perkhidmatan atau kewajipan undang-undang berubah dan akan memaparkan tarikh kemas kini di sini. Sila hubungi kami terlebih dahulu jika anda mempunyai kebimbangan supaya kami boleh menyiasat. Anda juga boleh menghubungi Jabatan Perlindungan Data Peribadi Malaysia.</p></section>
    </LegalShell>
  );
}
