import type { Metadata } from "next";
import { LegalShell } from "../../legal-shell";

export const metadata: Metadata = { title: "Jaminan Penjagaan — Washd", description: "Cara Washd merekod, menjaga dan menyiasat isu berkaitan dobi anda.", alternates: { canonical: "/care-guarantee/bm", languages: { "en-MY": "/care-guarantee", "ms-MY": "/care-guarantee/bm", "zh-CN": "/care-guarantee/zh", "ko-KR": "/care-guarantee/ko" } } };

export default function CareGuaranteeBmPage() {
  return <LegalShell policyPath="/care-guarantee" locale="ms" eyebrow="Dijejak dan dipertanggungjawabkan" title="Jaminan Penjagaan Washd" intro="Proses beg bernombor dan sejarah perkhidmatan kami direka supaya dobi setiap ahli dapat dikenal pasti dari pengumpulan hingga pemulangan.">
    <section><h2>Janji kami</h2><ul><li>Setiap pengumpulan dikaitkan dengan pengenal ahli dan beg anda.</li><li>Pengumpulan dan peringkat pengendalian utama direkodkan dalam sejarah perkhidmatan.</li><li>Setiap muatan basuhan dikendalikan berasingan kecuali anda bersetuju dengan jelas sebaliknya.</li><li>Kami mengikuti label penjagaan dan amalan penjagaan pakaian profesional yang munasabah.</li><li>Barangan hilang atau rosak yang dilaporkan disiasat menggunakan rekod pengumpulan, kiraan, gambar dan penjejakan yang tersedia.</li></ul></section>
    <section><h2>Sebelum menyerahkan beg</h2><p>Kosongkan semua poket dan keluarkan barang berharga, wang tunai, barang kemas, dokumen, elektronik dan benda tajam. Pastikan barangan sesuai bagi perkhidmatan dipilih. Maklumkan secara bertulis tentang bahan halus, hiasan longgar, pakaian bernilai, kotoran atau arahan khas sebelum pengumpulan. Barangan tanpa label penjagaan yang boleh dibaca diproses menggunakan pertimbangan profesional yang munasabah atas risiko pelanggan.</p></section>
    <section><h2>Cara melaporkan isu</h2><p>Periksa barangan sebaik sahaja dipulangkan dan laporkan kehilangan atau kerosakan dalam masa 24 jam selepas menerima beg yang dipulangkan. E-mel <a href="mailto:washdmy@gmail.com?subject=Permintaan%20Jaminan%20Penjagaan">washdmy@gmail.com</a> atau WhatsApp <a href="https://wa.me/60176494749">017-649 4749</a> dengan ID ahli, ID beg, tarikh pengumpulan, perihalan barangan dan gambar yang jelas. Simpan barangan dan pembungkusan semasa siasatan.</p></section>
    <section><h2>Tindakan seterusnya</h2><p>Kami menyasarkan untuk mengakui penerimaan dan memberikan kemas kini awal siasatan dalam masa 48 jam. Bergantung pada bukti dan keadaan, remedi yang adil boleh merangkumi pembersihan atau gosokan semula, kredit perkhidmatan, bayaran balik bagi perkhidmatan terjejas, pembaikan atau pampasan berdasarkan nilai semasa barangan yang munasabah. Kami mungkin meminta bukti pembelian, umur atau keadaan.</p></section>
    <section><h2>Perkara yang tidak dilindungi</h2><p>Jaminan tidak melindungi haus biasa, kerosakan sedia ada, kelemahan fabrik, kehilangan warna atau pengecutan walaupun label penjagaan diikuti, keperluan khas yang tidak dimaklumkan, kotoran yang tidak boleh ditanggalkan, barangan berharga dalam poket, barangan tidak selamat atau dilarang, atau isu yang dilaporkan terlalu lewat untuk disiasat secara munasabah. Setiap permintaan dinilai berdasarkan faktanya.</p></section>
    <section><h2>Hak statutori anda</h2><p>Jaminan ini ialah komitmen perkhidmatan tambahan. Ia tidak menghapuskan atau mengurangkan hak atau remedi yang tidak boleh dikecualikan di bawah undang-undang Malaysia yang terpakai.</p></section>
  </LegalShell>;
}
